TRAINING_DATA = [
    ("Installation of Mysql Workbench | TYPE: Act", {'entities': [(0, 12, 'TASK'), (16, 31, 'SOFTWARE'), (31, 43, 'TYPE')]}),
    ("Installation of Mongo DB | TYPE: Act", {'entities': [(0, 12, 'TASK'), (16, 24, 'SOFTWARE'), (24, 36, 'TYPE')]}),
    ("WASP Request for NodeJS software and MongoDB for project learning.", {'entities': [(5, 12, 'TASK'), (17, 23, 'SOFTWARE'), (45, 66, 'JUSTIFICATIONS'), (37, 44, 'SOFTWARE')]}),
    ("Installation of Maven | TYPE: Act", {'entities': [(0, 12, 'TASK'), (16, 21, 'SOFTWARE'), (21, 33, 'TYPE')]}),
    ("Installation of Open JDK | TYPE: Act", {'entities': [(0, 12, 'TASK'), (16, 24, 'SOFTWARE'), (24, 36, 'TYPE')]}),
    ("HI Team, kindly help install software _x000D_ | TYPE: Act | PACKAGES: SessionManagerPluginSetup_x000D | PACKAGES: AWSCLIV2_x000D | PACKAGES: AmazonSSMAgentSetup", {'entities': [(21, 28, 'TASK'), (57, 101, 'PACKAGES'), (101, 128, 'PACKAGES'), (128, 160, 'PACKAGES')]}),
    ("software installation | TYPE: Act", {'entities': [(9, 21, 'TASK'), (21, 33, 'TYPE')]}),
    ("I need putty access for the business purposes.", {'entities': [(13, 19, 'TASK'), (7, 12, 'SOFTWARE'), (28, 45, 'JUSTIFICATIONS')]}),
    ("Please install node.js in my machine | TYPE: Act", {'entities': [(7, 14, 'TASK'), (15, 22, 'SOFTWARE'), (36, 48, 'TYPE'), (29, 36, 'TARGETS')]}),
    ("Installation of the Mysql | TYPE: Act", {'entities': [(0, 12, 'TASK'), (20, 25, 'SOFTWARE'), (25, 37, 'TYPE')]}),
    ("Installation of the MAVEN | TYPE: Act", {'entities': [(0, 12, 'TASK'), (20, 25, 'SOFTWARE'), (25, 37, 'TYPE')]}),
    ("Installation of the Nodejs 20.2 | TYPE: Act", {'entities': [(0, 12, 'TASK'), (20, 26, 'SOFTWARE'), (31, 43, 'TYPE'), (27, 31, 'VERSIONS')]}),
    ("Installation of the STS | TYPE: Act", {'entities': [(0, 12, 'TASK'), (20, 23, 'SOFTWARE'), (23, 35, 'TYPE')]}),
    ("software installation .netcore 6 | TYPE: Act", {'entities': [(9, 21, 'TASK'), (22, 30, 'SOFTWARE'), (32, 44, 'TYPE'), (31, 32, 'VERSIONS')]}),
    ("Please help with Power BI installation and set-up to learn and practice power BI dashboards creation and all.", {'entities': [(26, 38, 'TASK'), (17, 25, 'SOFTWARE'), (50, 71, 'JUSTIFICATIONS')]}),
    ("Installation of the Opebjdk | SOFTWARE: openjdk | TYPE: Act", {'entities': [(0, 12, 'TASK'), (27, 47, 'SOFTWARE'), (47, 59, 'TYPE')]}),
    ("Installation of the  ApacheTomcat 10.1.0 | TYPE: Act", {'entities': [(0, 12, 'TASK'), (21, 33, 'SOFTWARE'), (40, 52, 'TYPE'), (34, 40, 'VERSIONS')]}),
    ("Need to install ProHance in My machine | TYPE: Act", {'entities': [(8, 15, 'TASK'), (16, 24, 'SOFTWARE'), (38, 50, 'TYPE'), (31, 38, 'TARGETS')]}),
    ("FortiClientMiniSetup-Windows-x64-Enterprise-7.2.3 - Need to install this software with Admin user. | TYPE: Act", {'entities': [(60, 67, 'TASK'), (0, 28, 'SOFTWARE'), (98, 110, 'TYPE'), (33, 49, 'VERSIONS'), (33, 43, 'LICENSES')]}),
    ("Istallation of the Openjdk | TYPE: Act", {'entities': [(0, 11, 'TASK'), (19, 26, 'SOFTWARE'), (26, 38, 'TYPE')]}),
    ("i need  open jdk software to complete mandatory training", {'entities': [(8, 16, 'SOFTWARE'), (26, 56, 'JUSTIFICATIONS')]}),
    ("Installation of Open jdk | TYPE: Act", {'entities': [(0, 12, 'TASK'), (16, 24, 'SOFTWARE'), (24, 36, 'TYPE')]}),
    ("Install .net 7.0 | TYPE: Act", {'entities': [(0, 7, 'TASK'), (8, 12, 'SOFTWARE'), (16, 28, 'TYPE'), (13, 16, 'VERSIONS')]}),
    ("Removal of Java 21 | TYPE: Act", {'entities': [(0, 7, 'TASK'), (11, 15, 'SOFTWARE'), (18, 30, 'TYPE'), (16, 18, 'VERSIONS')]}),
    ("Installation of Java 17 | TYPE: Act", {'entities': [(0, 12, 'TASK'), (16, 20, 'SOFTWARE'), (23, 35, 'TYPE'), (21, 23, 'VERSIONS')]}),
    ("Need help in installing the Ctirix version 2405 | SOFTWARE: citrix | TYPE: Act", {'entities': [(13, 23, 'TASK'), (47, 66, 'SOFTWARE'), (66, 78, 'TYPE'), (43, 47, 'VERSIONS')]}),
    ("Visio installation | TYPE: Act", {'entities': [(6, 18, 'TASK'), (0, 5, 'SOFTWARE'), (18, 30, 'TYPE')]}),
    ("manual installation of SSMS againstWASP-Operations Team approval | TYPE: Act", {'entities': [(7, 19, 'TASK'), (24, 28, 'SOFTWARE'), (69, 81, 'TYPE'), (78, 81, 'TYPE')]}),
    ("How to install software on a laptop? | TYPE: Act", {'entities': [(7, 14, 'TASK'), (0, 6, 'TYPE'), (36, 48, 'TYPE'), (29, 35, 'TARGETS')]}),
    ("Require java 1.8 to complete assignments and learning. | TYPE: Act", {'entities': [(0, 7, 'TASK'), (8, 12, 'SOFTWARE'), (54, 66, 'TYPE'), (13, 16, 'VERSIONS'), (17, 28, 'JUSTIFICATIONS'), (20, 40, 'JUSTIFICATIONS')]}),
    ("need to install softwares eclipse, jdk and sql work bench latest version | TYPE: Act", {'entities': [(8, 15, 'TASK'), (26, 33, 'SOFTWARE'), (72, 84, 'TYPE'), (58, 64, 'VERSIONS'), (35, 38, 'SOFTWARE'), (81, 84, 'TYPE'), (43, 57, 'SOFTWARE')]}),
    ("Installation of Appium GUI Server and Appium Inspector | TYPE: Act", {'entities': [(0, 12, 'TASK'), (16, 33, 'SOFTWARE'), (54, 66, 'TYPE'), (27, 33, 'TARGETS'), (38, 54, 'SOFTWARE'), (63, 66, 'TYPE')]}),
    ("I need to download eclipse IDE | TYPE: Act", {'entities': [(10, 18, 'TASK'), (19, 26, 'SOFTWARE'), (30, 42, 'TYPE')]}),
    ("install putty and notepad ++ in my machine | TYPE: Act", {'entities': [(0, 7, 'TASK'), (8, 13, 'SOFTWARE'), (42, 54, 'TYPE'), (35, 42, 'TARGETS'), (18, 28, 'SOFTWARE'), (51, 54, 'TYPE')]}),
    ("installation of SF CLI | TYPE: Act", {'entities': [(0, 12, 'TASK'), (16, 22, 'SOFTWARE'), (22, 34, 'TYPE')]}),
    ("manual installation of  Microsoft Visual studio  enterprice with msdn  against WASP-Operations Team approval . | TYPE: Act | LICENSES: Enterprise", {'entities': [(7, 19, 'TASK'), (24, 47, 'SOFTWARE'), (110, 122, 'TYPE'), (119, 122, 'TYPE'), (122, 145, 'LICENSES'), (65, 69, 'SOFTWARE'), (135, 145, 'LICENSES')]}),
    ("Need to install nvm and node modules for project work in my local system | TYPE: Act", {'entities': [(8, 15, 'TASK'), (16, 19, 'SOFTWARE'), (72, 84, 'TYPE'), (60, 72, 'TARGETS'), (37, 53, 'JUSTIFICATIONS'), (24, 36, 'SOFTWARE'), (81, 84, 'TYPE')]}),
    ("installation of IDE Eclipse | TYPE: Act", {'entities': [(0, 12, 'TASK'), (16, 27, 'SOFTWARE'), (27, 39, 'TYPE')]}),
    ("Hi Team, | TASK: install | SOFTWARE: Java | TYPE: Act | TARGETS: system | JUSTIFICATIONS: to work on Spring tool suite | SOFTWARE: JDK", {'entities': [(8, 24, 'TASK'), (24, 41, 'SOFTWARE'), (41, 53, 'TYPE'), (53, 71, 'TARGETS'), (71, 118, 'JUSTIFICATIONS'), (17, 24, 'TASK'), (118, 134, 'SOFTWARE'), (50, 53, 'TYPE'), (65, 71, 'TARGETS'), (90, 118, 'JUSTIFICATIONS')]}),
    ("Oracle database 19c reinstallation | TYPE: Act", {'entities': [(20, 34, 'TASK'), (0, 15, 'SOFTWARE'), (34, 46, 'TYPE'), (16, 19, 'VERSIONS')]}),
    ("MySql not getting installed | TYPE: Act", {'entities': [(18, 27, 'TASK'), (0, 5, 'SOFTWARE'), (6, 27, 'TYPE'), (27, 39, 'TYPE')]}),
    ("Installatin of the Power BI | TYPE: Act", {'entities': [(0, 11, 'TASK'), (19, 27, 'SOFTWARE'), (27, 39, 'TYPE')]}),
    ("Installation of Open JDK 22 | TYPE: Act", {'entities': [(0, 12, 'TASK'), (16, 24, 'SOFTWARE'), (27, 39, 'TYPE'), (25, 27, 'VERSIONS')]}),
    ("Install notepad++ | TYPE: Act", {'entities': [(0, 7, 'TASK'), (8, 17, 'SOFTWARE'), (17, 29, 'TYPE')]}),
    ("How to install software? | TYPE: Act", {'entities': [(7, 14, 'TASK'), (0, 6, 'TYPE'), (24, 36, 'TYPE')]}),
    ("No - INC11203012", {'entities': [(5, 8, 'SOFTWARE'), (8, 16, 'VERSIONS')]}),
    ("I got new windows book. I need assistance to download and install the necessary apps | TYPE: Act", {'entities': [(45, 53, 'TASK'), (84, 96, 'TYPE'), (93, 96, 'TYPE'), (10, 22, 'TARGETS')]}),
    ("i am not able to use this software AWSCLIV2", {'entities': [(35, 43, 'SOFTWARE'), (5, 16, 'TYPE'), (35, 43, 'PACKAGES'), (42, 43, 'VERSIONS'), (14, 20, 'JUSTIFICATIONS')]}),
    ("I need to install node js software in my machine. Need admin creds to proceed with the installation. | TYPE: Act", {'entities': [(87, 99, 'TASK'), (18, 25, 'SOFTWARE'), (100, 112, 'TYPE'), (109, 112, 'TYPE'), (41, 48, 'TARGETS'), (55, 66, 'JUSTIFICATIONS')]}),
    ("Install Excel in my laptop | TYPE: Act", {'entities': [(0, 7, 'TASK'), (8, 13, 'SOFTWARE'), (26, 38, 'TYPE'), (20, 26, 'TARGETS')]}),
    ("I am not able to download the dependences while the doing mvn clean install. Please can look at this issue. maybe it has network issue. | TYPE: Act", {'entities': [(17, 25, 'TASK'), (58, 75, 'SOFTWARE'), (5, 16, 'TYPE'), (135, 147, 'TYPE'), (144, 147, 'TYPE'), (121, 128, 'TARGETS')]}),
    ("As per client requirement please upgrade VDI version 8.12.1 or greater. | TYPE: Act", {'entities': [(33, 40, 'TASK'), (41, 44, 'SOFTWARE'), (71, 83, 'TYPE'), (80, 83, 'TYPE'), (53, 59, 'VERSIONS'), (41, 44, 'TARGETS')]}),
    ("Need Microsoft teams & citrix installed | TYPE: Act", {'entities': [(30, 39, 'TASK'), (5, 20, 'SOFTWARE'), (39, 51, 'TYPE'), (23, 29, 'SOFTWARE'), (48, 51, 'TYPE')]}),
    ("Installation of the  VISIO2019 | TYPE: Act", {'entities': [(0, 12, 'TASK'), (21, 26, 'SOFTWARE'), (30, 42, 'TYPE'), (26, 30, 'VERSIONS')]}),
    ("Unable to install PUTTY Application in my laptop | TYPE: Not able to | TYPE: Act", {'entities': [(10, 17, 'TASK'), (18, 23, 'SOFTWARE'), (48, 68, 'TYPE'), (68, 80, 'TYPE'), (42, 48, 'TARGETS')]}),
    ("Need to install Pycharm IDE and Robot Framework 7.0.1 for python training. | TYPE: Act", {'entities': [(8, 15, 'TASK'), (16, 23, 'SOFTWARE'), (74, 86, 'TYPE'), (48, 53, 'VERSIONS'), (54, 73, 'JUSTIFICATIONS'), (32, 47, 'SOFTWARE'), (83, 86, 'TYPE'), (58, 64, 'SOFTWARE')]}),
    ("Hi,_x000D_ | TASK: access | SOFTWARE: ms teams | TYPE: Act | TARGETS: laptop | SOFTWARE: outlook", {'entities': [(10, 25, 'TASK'), (25, 46, 'SOFTWARE'), (46, 58, 'TYPE'), (58, 76, 'TARGETS'), (19, 25, 'TASK'), (76, 96, 'SOFTWARE'), (55, 58, 'TYPE'), (70, 76, 'TARGETS')]}),
    ("wanted to install Cisco Packet Tracer 8.2.2 Windows 64bit | TYPE: Act", {'entities': [(10, 17, 'TASK'), (18, 37, 'SOFTWARE'), (57, 69, 'TYPE'), (38, 43, 'VERSIONS')]}),
    ("installation of sql developer | TYPE: Act", {'entities': [(0, 12, 'TASK'), (16, 29, 'SOFTWARE'), (29, 41, 'TYPE')]}),
    ("Please install global protect version 5.2.6-87 in my laptop | TYPE: Act", {'entities': [(7, 14, 'TASK'), (15, 29, 'SOFTWARE'), (59, 71, 'TYPE'), (38, 43, 'VERSIONS'), (44, 46, 'VERSIONS'), (53, 59, 'TARGETS')]}),
    ("new teams installation | TYPE: Act", {'entities': [(10, 22, 'TASK'), (4, 9, 'SOFTWARE'), (22, 34, 'TYPE')]}),
    ("How to connect with a live agent?", {'entities': [(0, 6, 'TYPE'), (7, 14, 'TYPE')]}),
    ("Install Excel application in my system | TYPE: Act", {'entities': [(0, 7, 'TASK'), (8, 13, 'SOFTWARE'), (38, 50, 'TYPE'), (32, 38, 'TARGETS')]}),
    ("Libreoffice installation | TYPE: Act", {'entities': [(12, 24, 'TASK'), (0, 11, 'SOFTWARE'), (24, 36, 'TYPE')]}),
    ("Installation of the  Openjdk22.0 | TYPE: Act", {'entities': [(0, 12, 'TASK'), (21, 28, 'SOFTWARE'), (32, 44, 'TYPE'), (28, 32, 'VERSIONS')]}),
    ("Software Installation   oracle 21 C | TYPE: Act", {'entities': [(9, 21, 'TASK'), (24, 30, 'SOFTWARE'), (35, 47, 'TYPE'), (31, 33, 'VERSIONS')]}),
    ("Software Installation  power BI publisher latest _x000D_ | TYPE: Act", {'entities': [(9, 21, 'TASK'), (23, 31, 'SOFTWARE'), (56, 68, 'TYPE'), (42, 48, 'VERSIONS')]}),
    ("need to install vs code | TYPE: Act", {'entities': [(8, 15, 'TASK'), (16, 23, 'SOFTWARE'), (23, 35, 'TYPE')]}),
    ("Chrome extension enable", {'entities': [(17, 23, 'TASK'), (0, 16, 'SOFTWARE'), (17, 23, 'TYPE')]}),
    ("require admin acess to install angular cli | TYPE: Act", {'entities': [(0, 7, 'TASK'), (31, 38, 'SOFTWARE'), (42, 54, 'TYPE'), (51, 54, 'TYPE')]}),
    ("software installation  excel  | TYPE: Act", {'entities': [(9, 21, 'TASK'), (23, 28, 'SOFTWARE'), (29, 41, 'TYPE')]}),
    ("Chevron Virtual Workspace (CVW)", {'entities': [(27, 30, 'SOFTWARE'), (8, 25, 'TARGETS')]}),
    ("I want software installation in my laptop for project requirement. | TYPE: Act", {'entities': [(16, 28, 'TASK'), (66, 78, 'TYPE'), (75, 78, 'TYPE'), (35, 41, 'TARGETS'), (42, 53, 'JUSTIFICATIONS')]}),
    ("Hi Team , | TASK: download | SOFTWARE: Cisco Jabber | TYPE: Act | TARGETS: System | LICENSES: free", {'entities': [(9, 26, 'TASK'), (26, 51, 'SOFTWARE'), (51, 63, 'TYPE'), (60, 63, 'TYPE'), (63, 81, 'TARGETS'), (81, 98, 'LICENSES')]}),
    ("_x000D_ | TASK: installation | SOFTWARE: Microsoft Visio | TYPE: Act | LICENSES: Professional", {'entities': [(7, 28, 'TASK'), (28, 56, 'SOFTWARE'), (56, 68, 'TYPE'),(68, 93, 'LICENSES')]}),
    ("manual installation of  Adobe Acrobat Professional DC  against WASP-Operations Team approval . | TYPE: Act", {'entities': [(7, 19, 'TASK'), (24, 37, 'SOFTWARE'), (94, 106, 'TYPE'), (103, 106, 'TYPE'), (38, 50, 'LICENSES')]}),
    ("laptop fermented need to install all the software | TYPE: Act", {'entities': [(25, 32, 'TASK'), (49, 61, 'TYPE'), (0, 6, 'TARGETS')]}),
    ("Hi Team, kindly help me to install postman software on my laptop as per client requested thanks | TYPE: Act", {'entities': [(27, 34, 'TASK'), (35, 42, 'SOFTWARE'), (95, 107, 'TYPE'), (58, 64, 'TARGETS'), (72, 88, 'JUSTIFICATIONS')]}),
    ("I want to install Android Studio. | TYPE: Act", {'entities': [(10, 17, 'TASK'), (18, 32, 'SOFTWARE'), (33, 45, 'TYPE')]}),
    ("manual installation of  Microsoft Visio Professional 2019  against WASP-Operations Team approval ._x000D_ | TYPE: Act", {'entities': [(7, 19, 'TASK'), (24, 39, 'SOFTWARE'), (105, 117, 'TYPE'), (114, 117, 'TYPE'), (53, 57, 'VERSIONS'), (40, 52, 'LICENSES')]}),
    ("please help me with the power bi desktop application installation | TYPE: Act", {'entities': [(53, 65, 'TASK'), (24, 32, 'SOFTWARE'), (65, 77, 'TYPE'), (33, 40, 'TARGETS')]}),
    ("AVAYA Workspace installation | TYPE: Act", {'entities': [(16, 28, 'TASK'), (0, 15, 'SOFTWARE'), (28, 40, 'TYPE'), (6, 15, 'TARGETS')]}),
    ("software installation for node js | TYPE: Act", {'entities': [(9, 21, 'TASK'), (26, 33, 'SOFTWARE'), (33, 45, 'TYPE')]}),
    ("Please install git to my system | TYPE: Act", {'entities': [(7, 14, 'TASK'), (15, 18, 'SOFTWARE'), (31, 43, 'TYPE'), (25, 31, 'TARGETS')]}),
    ("Need to install Python for Python training | TYPE: Act", {'entities': [(8, 15, 'TASK'), (16, 22, 'SOFTWARE'), (42, 54, 'TYPE'), (23, 42, 'JUSTIFICATIONS')]}),
    ("Installation of the  Postgresql16.0 | TYPE: Act", {'entities': [(0, 12, 'TASK'), (21, 31, 'SOFTWARE'), (35, 47, 'TYPE'), (31, 35, 'VERSIONS')]}),
    ("manual installation of   Microsoft Visio standard  against WASP-Operations Team approval . | TYPE: Act", {'entities': [(7, 19, 'TASK'), (25, 40, 'SOFTWARE'), (90, 102, 'TYPE'), (99, 102, 'TYPE'), (41, 49, 'LICENSES')]}),
    ("manual installation of  Microsoft Visual studio Professional with MSDN  against WASP-Operations Team approval . | TYPE: Act", {'entities': [(7, 19, 'TASK'), (24, 47, 'SOFTWARE'), (111, 123, 'TYPE'), (120, 123, 'TYPE'), (48, 60, 'LICENSES'), (66, 70, 'SOFTWARE')]}),
    ("SAP GUI Logon Pad 8.00 version should be install | TYPE: Act | SOFTWARE: Zscaler | SOFTWARE: Global protect", {'entities': [(41, 48, 'TASK'), (0, 17, 'SOFTWARE'), (48, 60, 'TYPE'), (57, 60, 'TYPE'), (18, 22, 'VERSIONS'), (60, 80, 'SOFTWARE'), (80, 107, 'SOFTWARE')]}),
    ("Node.js software installation. | TYPE: Act", {'entities': [(17, 29, 'TASK'), (0, 7, 'SOFTWARE'), (30, 42, 'TYPE')]}),
    ("software installation in global protect version 5.2.10 and after it is connected, the system restarts or shut down. | TYPE: Act", {'entities': [(9, 21, 'TASK'), (25, 39, 'SOFTWARE'), (115, 127, 'TYPE'), (48, 54, 'VERSIONS'), (86, 92, 'TARGETS')]}),
    ("Need notepad++ installation | TYPE: Act", {'entities': [(15, 27, 'TASK'), (5, 14, 'SOFTWARE'), (27, 39, 'TYPE')]}),
    ("Need remote desktop installed on my machine. | TYPE: Act", {'entities': [(20, 29, 'TASK'), (5, 19, 'SOFTWARE'), (44, 56, 'TYPE'), (36, 43, 'TARGETS')]}),
    ("Hi Team, | TASK: access | SOFTWARE: amazon workspace | TYPE: Act", {'entities': [(8, 23, 'TASK'), (23, 52, 'SOFTWARE'), (52, 64, 'TYPE'), (43, 52, 'TARGETS')]}),
    ("install git and postman for project work | TYPE: Act", {'entities': [(0, 7, 'TASK'), (8, 11, 'SOFTWARE'), (40, 52, 'TYPE'), (24, 40, 'JUSTIFICATIONS'), (16, 23, 'SOFTWARE'), (49, 52, 'TYPE')]}),
    ("Hi Team,_x000D_ | SOFTWARE: Postgresql | SOFTWARE: Pgadmin", {'entities': [(15, 38, 'SOFTWARE'), (38, 58, 'SOFTWARE')]}),
    ("MS Teams ,One drive and Remote Desktop to be installed in | TYPE: Act | TARGETS: host", {'entities': [(45, 54, 'TASK'), (24, 38, 'SOFTWARE'), (57, 69, 'TYPE'), (69, 85, 'TARGETS'), (0, 8, 'SOFTWARE'), (66, 69, 'TYPE'), (81, 85, 'TARGETS'), (10, 19, 'SOFTWARE')]}),
    ("cannot be able to raise request regarding software installation | TYPE: Act", {'entities': [(24, 31, 'TASK'), (63, 75, 'TYPE')]}),
    ("Team, please help in getting Pycharm software installed, which is IDE for Pyhton. | TYPE: Act", {'entities': [(46, 55, 'TASK'), (29, 36, 'SOFTWARE'), (81, 93, 'TYPE')]}),
    ("I need to install oracle virtual box on laptop. | TYPE: Act", {'entities': [(10, 17, 'TASK'), (18, 36, 'SOFTWARE'), (47, 59, 'TYPE'), (40, 46, 'TARGETS')]}),
    ("software installation | TYPE: Act", {'entities': [(9, 21, 'TASK'), (21, 33, 'TYPE')]}),
    ("Installation of the Microsoft SQL Server Management Studio 18.11.1 | TYPE: Act", {'entities': [(0, 12, 'TASK'), (30, 58, 'SOFTWARE'), (66, 78, 'TYPE'), (59, 66, 'VERSIONS'), (34, 40, 'TARGETS')]}),
    ("Installation of the  Microsoft SQL Server Express 2019 | TYPE: Act", {'entities': [(0, 12, 'TASK'), (31, 49, 'SOFTWARE'), (54, 66, 'TYPE'), (50, 54, 'VERSIONS'), (35, 41, 'TARGETS')]}),
    ("Installation of the  Microsoft Visual Studio Enterprise with Github 2022 | TYPE: Act", {'entities': [(0, 12, 'TASK'), (21, 44, 'SOFTWARE'), (72, 84, 'TYPE'), (68, 72, 'VERSIONS'), (45, 55, 'LICENSES'), (61, 67, 'SOFTWARE'), (81, 84, 'TYPE')]}),
    ("Hi Team, Please install java openjdk software. Regards Siddesh | TYPE: Act", {'entities': [(16, 23, 'TASK'), (24, 28, 'SOFTWARE'), (62, 74, 'TYPE'), (29, 36, 'SOFTWARE'), (71, 74, 'TYPE')]}),
    ("Please help to install anaconda in windows server._x000D_ | TYPE: Act", {'entities': [(15, 22, 'TASK'), (23, 31, 'SOFTWARE'), (57, 69, 'TYPE')]}),
    ("Installation of the  Adobe Acrobat Professional DC 202 | TYPE: Act", {'entities': [(0, 12, 'TASK'), (21, 34, 'SOFTWARE'), (54, 66, 'TYPE'), (51, 54, 'VERSIONS'), (35, 47, 'LICENSES')]}),
    ("Dear Team,_x000D_ | TASK: install | SOFTWARE: JAVA JDK | TYPE: Act", {'entities': [(17, 33, 'TASK'), (33, 54, 'SOFTWARE'), (54, 66, 'TYPE')]}),
    ("I need Docker application for learn DevOps..", {'entities': [(7, 13, 'SOFTWARE'), (26, 44, 'JUSTIFICATIONS')]}),
    ("manual installation of  Node.js  against WASP-Operations Team approval . | TYPE: Act", {'entities': [(7, 19, 'TASK'), (24, 31, 'SOFTWARE'), (72, 84, 'TYPE'), (81, 84, 'TYPE')]}),
    ("manual installation of  Microsoft .netframework  against WASP-Operations Team approval . | TYPE: Act", {'entities': [(7, 19, 'TASK'), (34, 47, 'SOFTWARE'), (88, 100, 'TYPE'), (97, 100, 'TYPE')]}),
    ("manual installation of  Microstation  against WASP-Operations Team approval . | TYPE: Act", {'entities': [(7, 19, 'TASK'), (24, 36, 'SOFTWARE'), (77, 89, 'TYPE'), (86, 89, 'TYPE')]}),
    ("manual installation of  AUTOSAS  against WASP-Operations Team approval . | TYPE: Act", {'entities': [(7, 19, 'TASK'), (24, 31, 'SOFTWARE'), (72, 84, 'TYPE'), (81, 84, 'TYPE')]}),
    ("How to create an IT request?", {'entities': [(20, 27, 'TASK'), (0, 6, 'TYPE')]}),
    ("manual installation of  AUTOSAS  against WASP-Operations Team approval ._x000D_ | TYPE: Act", {'entities': [(7, 19, 'TASK'), (24, 31, 'SOFTWARE'), (79, 91, 'TYPE'), (88, 91, 'TYPE')]}),
    ("manual installation of  AUTOSAS  against WASP-Operations Team approval ._x000D_ | TYPE: Act", {'entities': [(7, 19, 'TASK'), (24, 31, 'SOFTWARE'), (79, 91, 'TYPE'), (88, 91, 'TYPE')]}),
    ("I need to install | TYPE: Act", {'entities': [(10, 17, 'TASK'), (17, 29, 'TYPE')]}),
    ("manual installation of  AUTOSAS  against WASP-Operations Team approval . | TYPE: Act", {'entities': [(7, 19, 'TASK'), (24, 31, 'SOFTWARE'), (72, 84, 'TYPE'), (81, 84, 'TYPE')]}),
    ("manual installation of  AUTOSAS  against WASP-Operations Team approval . | TYPE: Act", {'entities': [(7, 19, 'TASK'), (24, 31, 'SOFTWARE'), (72, 84, 'TYPE'), (81, 84, 'TYPE')]}),
    ("manual installation of  AutoSAS  against WASP-Operations Team approval . | TYPE: Act", {'entities': [(7, 19, 'TASK'), (24, 31, 'SOFTWARE'), (72, 84, 'TYPE'), (81, 84, 'TYPE')]}),
    ("Installation of Eclipse 2024 | TYPE: Act", {'entities': [(0, 12, 'TASK'), (16, 23, 'SOFTWARE'), (28, 40, 'TYPE'), (24, 28, 'VERSIONS')]}),
    ("manual installation of  Storyline  against WASP-Operations Team approval ._x000D_ | TYPE: Act", {'entities': [(7, 19, 'TASK'), (24, 33, 'SOFTWARE'), (81, 93, 'TYPE'), (90, 93, 'TYPE')]}),
    ("Need to install ARCON app | TYPE: Act", {'entities': [(8, 15, 'TASK'), (16, 21, 'SOFTWARE'), (25, 37, 'TYPE')]}),
    ("manual installation of  Articulate 360  against WASP-Operations Team approval . | TYPE: Act", {'entities': [(7, 19, 'TASK'), (24, 34, 'SOFTWARE'), (79, 91, 'TYPE'), (88, 91, 'TYPE'), (35, 38, 'VERSIONS')]}),
    ("Notepad++ installation | TYPE: Act", {'entities': [(10, 22, 'TASK'), (0, 9, 'SOFTWARE'), (22, 34, 'TYPE')]}),
    ("Software Installation putty 0.81 | TYPE: Act", {'entities': [(9, 21, 'TASK'), (22, 27, 'SOFTWARE'), (32, 44, 'TYPE'), (28, 32, 'VERSIONS')]}),
    ("Hi, | TASK: installed | SOFTWARE: MS Visio | TYPE: Act | TARGETS: Laptop", {'entities': [(3, 21, 'TASK'), (21, 42, 'SOFTWARE'), (42, 54, 'TYPE'), (54, 72, 'TARGETS')]}),
    ("Angular CLI Installation | TYPE: Act", {'entities': [(12, 24, 'TASK'), (0, 7, 'SOFTWARE'), (24, 36, 'TYPE')]}),
    ("Require support staff assistance to install apps | TYPE: Act", {'entities': [(0, 7, 'TASK'), (48, 60, 'TYPE'), (57, 60, 'TYPE')]}),
    ("Hi Team, I've got installed SSMS and SQL server but still I'm not able to find server name/instance . Thats why I'm not able to connect with DB with server. Please help me to resolve this issue. | TYPE: Act", {'entities': [(18, 27, 'TASK'), (37, 47, 'SOFTWARE'), (194, 206, 'TYPE'), (62, 73, 'TYPE'), (128, 135, 'TYPE'), (41, 47, 'TARGETS'), (91, 99, 'TARGETS'), (28, 32, 'SOFTWARE'), (203, 206, 'TYPE')]}),
    ("Python libraries are not getting installed | TYPE: Act", {'entities': [(33, 42, 'TASK'), (0, 6, 'SOFTWARE'), (21, 42, 'TYPE'), (42, 54, 'TYPE')]}),
    ("install a software Oracle OpenJDK 22.0.1 (aarch64) | TYPE: Act", {'entities': [(0, 7, 'TASK'), (19, 33, 'SOFTWARE'), (50, 62, 'TYPE'), (34, 40, 'VERSIONS')]}),
    ("I want to install IntelliJ in my system | TYPE: Act", {'entities': [(10, 17, 'TASK'), (18, 26, 'SOFTWARE'), (39, 51, 'TYPE'), (33, 39, 'TARGETS')]}),
    ("minitab installation | TYPE: Act", {'entities': [(8, 20, 'TASK'), (0, 7, 'SOFTWARE'), (20, 32, 'TYPE')]}),
    ("Software Installation : Matrix | TYPE: Act", {'entities': [(9, 21, 'TASK'), (24, 30, 'SOFTWARE'), (30, 42, 'TYPE')]}),
    ("Could you please setup and install teams, outlook, google chorme, 7-Zip, MS Word, MS Excel. | TYPE: Act", {'entities': [(27, 34, 'TASK'), (35, 40, 'SOFTWARE'), (91, 103, 'TYPE'), (100, 103, 'TYPE'), (66, 67, 'VERSIONS'), (42, 49, 'SOFTWARE'), (51, 57, 'SOFTWARE'), (66, 71, 'SOFTWARE'), (76, 80, 'SOFTWARE'), (85, 90, 'SOFTWARE')]}),
    ("How to install AWS vpns client on a Windows laptop? | TYPE: Act", {'entities': [(7, 14, 'TASK'), (15, 18, 'SOFTWARE'), (0, 6, 'TYPE'), (51, 63, 'TYPE'), (44, 50, 'TARGETS')]}),
    ("could you please install below software | SOFTWARE: oracle | TYPE: Act | SOFTWARE: python | SOFTWARE: snowflake | SOFTWARE: notepad++", {'entities': [(17, 24, 'TASK'), (39, 58, 'SOFTWARE'), (58, 70, 'TYPE'), (70, 89, 'SOFTWARE'), (67, 70, 'TYPE'), (89, 111, 'SOFTWARE'), (111, 133, 'SOFTWARE')]}),
    ("I need to install Mysql on my local machine for internal POC. But when I am trying to install its asking Admin credential. | TYPE: Act", {'entities': [(10, 17, 'TASK'), (18, 23, 'SOFTWARE'), (122, 134, 'TYPE'), (131, 134, 'TYPE'), (30, 35, 'TARGETS')]}),
    ("Avaya agent installation | TYPE: Act", {'entities': [(12, 24, 'TASK'), (0, 11, 'SOFTWARE'), (24, 36, 'TYPE')]}),
    ("Software installation Citrix version 24.3.1.97 | TYPE: Act", {'entities': [(9, 21, 'TASK'), (22, 28, 'SOFTWARE'), (46, 58, 'TYPE'), (37, 46, 'VERSIONS')]}),
    ("Installation of the MSDN 2022 | TYPE: Act | SOFTWARE: node js | VERSIONS: 21", {'entities': [(0, 12, 'TASK'), (20, 24, 'SOFTWARE'), (29, 41, 'TYPE'), (25, 29, 'VERSIONS'), (41, 61, 'SOFTWARE'), (38, 41, 'TYPE'), (61, 76, 'VERSIONS')]}),
    ("need to install AZURE CLI | TYPE: Act", {'entities': [(8, 15, 'TASK'), (16, 25, 'SOFTWARE'), (25, 37, 'TYPE')]}),
    ("Hello, | TASK: access | SOFTWARE: Notepad++ | TYPE: Act | VERSIONS: 20532766 | SOFTWARE: Adobe Acrobat", {'entities': [(6, 21, 'TASK'), (21, 43, 'SOFTWARE'), (43, 55, 'TYPE'), (55, 76, 'VERSIONS'), (15, 21, 'TASK'), (76, 102, 'SOFTWARE'), (52, 55, 'TYPE'), (68, 76, 'VERSIONS')]}),
    ("need notepad ++ install on my laptop , kindly do the needful | TYPE: Act", {'entities': [(16, 23, 'TASK'), (5, 15, 'SOFTWARE'), (60, 72, 'TYPE'), (30, 36, 'TARGETS')]}),
    ("Software installation Citrix version 24.3.1.97 | TYPE: Act", {'entities': [(9, 21, 'TASK'), (22, 28, 'SOFTWARE'), (46, 58, 'TYPE'), (37, 46, 'VERSIONS')]}),
    ("In Ubuntu VM facing issue.", {'entities': [(10, 12, 'TARGETS')]}),
    ("install cisco-secure-client-win-5.1.3.62-predeploy-k9 | TYPE: Act", {'entities': [(0, 7, 'TASK'), (8, 27, 'SOFTWARE'), (53, 65, 'TYPE'), (28, 40, 'VERSIONS')]}),
    ("mfa repush for new mobile -9886455314", {'entities': []}),
    ("streamlit python", {'entities': [(0, 9, 'SOFTWARE'), (10, 16, 'SOFTWARE')]}),
    (" WINSCP _x000D_ | TASK: installation | TYPE: Act", {'entities': [(15, 36, 'TASK'), (36, 48, 'TYPE')]}),
    ("Citix workspace installation issue. | TYPE: Act", {'entities': [(16, 28, 'TASK'), (35, 47, 'TYPE'), (6, 15, 'TARGETS')]}),
    ("Getting issues while installing Docker in my laptop | TYPE: Act", {'entities': [(21, 31, 'TASK'), (32, 38, 'SOFTWARE'), (51, 63, 'TYPE'), (45, 51, 'TARGETS')]}),
    ("Please help to install streamlit library of python. | TASK: installed | TYPE: Act", {'entities': [(51, 69, 'TASK'), (23, 32, 'SOFTWARE'), (69, 81, 'TYPE'), (78, 81, 'TYPE'), (60, 69, 'TASK'), (44, 50, 'SOFTWARE')]}),
    ("manual installation of  Open JDK  against WASP-Operations Team approval . | TYPE: Act", {'entities': [(7, 19, 'TASK'), (24, 32, 'SOFTWARE'), (73, 85, 'TYPE'), (82, 85, 'TYPE')]}),
    ("I am not able to install python  packages in vscode | TYPE: Act", {'entities': [(17, 24, 'TASK'), (25, 31, 'SOFTWARE'), (5, 16, 'TYPE'), (51, 63, 'TYPE'), (45, 51, 'SOFTWARE'), (60, 63, 'TYPE')]}),
    ("To install visual studio | TYPE: Act", {'entities': [(3, 10, 'TASK'), (11, 24, 'SOFTWARE'), (24, 36, 'TYPE')]}),
    ("Unable to install the catalog software SOAPUI. | TYPE: Not able to | TYPE: Act", {'entities': [(10, 17, 'TASK'), (39, 45, 'SOFTWARE'), (46, 66, 'TYPE'), (66, 78, 'TYPE')]}),
    ("Software Installation Mysql 8.37 | TYPE: Act", {'entities': [(9, 21, 'TASK'), (22, 27, 'SOFTWARE'), (32, 44, 'TYPE'), (28, 32, 'VERSIONS')]}),
    ("Software Installation dbForge Studio For PostgreSQL 1.0.410 | TYPE: Act", {'entities': [(9, 21, 'TASK'), (22, 29, 'SOFTWARE'), (59, 71, 'TYPE'), (52, 59, 'VERSIONS'), (41, 51, 'SOFTWARE'), (68, 71, 'TYPE')]}),
    ("Hi, I want to get install Tableau public software into my laptop. Please help me to install that. | TYPE: Act", {'entities': [(18, 25, 'TASK'), (26, 40, 'SOFTWARE'), (97, 109, 'TYPE'), (106, 109, 'TYPE'), (58, 64, 'TARGETS')]}),
    ("Software Installation oracle 21 C | TYPE: Act", {'entities': [(9, 21, 'TASK'), (22, 28, 'SOFTWARE'), (33, 45, 'TYPE'), (29, 31, 'VERSIONS')]}),
    ("Software Installation open jdk 22 | TYPE: Act", {'entities': [(9, 21, 'TASK'), (22, 30, 'SOFTWARE'), (33, 45, 'TYPE'), (31, 33, 'VERSIONS')]}),
    ("Request to install Python and Anaconda on the device for training purpose. | TYPE: Act", {'entities': [(0, 7, 'TASK'), (19, 25, 'SOFTWARE'), (74, 86, 'TYPE'), (46, 52, 'TARGETS'), (30, 38, 'SOFTWARE'), (83, 86, 'TYPE')]}),
    ("Hi Team, I want to install JDK version 17 in my system for training purpose. | TYPE: Act", {'entities': [(19, 26, 'TASK'), (27, 30, 'SOFTWARE'), (76, 88, 'TYPE'), (39, 41, 'VERSIONS'), (48, 54, 'TARGETS')]}),
    ("How to install MySQL software? | TYPE: Act", {'entities': [(7, 14, 'TASK'), (15, 20, 'SOFTWARE'), (0, 6, 'TYPE'), (30, 42, 'TYPE')]}),
    ("Software Installation : oracle VM virtual box Mobaxterm home | TYPE: Act", {'entities': [(9, 21, 'TASK'), (24, 30, 'SOFTWARE'), (60, 72, 'TYPE'), (31, 33, 'TARGETS'), (34, 41, 'TARGETS'), (46, 55, 'SOFTWARE'), (69, 72, 'TYPE')]}),
    ("manual installation of  Microsoft Visio Professional  against WASP-Operations Team approval . | TYPE: Act", {'entities': [(7, 19, 'TASK'), (24, 39, 'SOFTWARE'), (93, 105, 'TYPE'), (102, 105, 'TYPE'), (40, 52, 'LICENSES')]}),
    ("I am unable to open VISIO which is already installed | TYPE: Not able to | TYPE: Act", {'entities': [(43, 52, 'TASK'), (20, 25, 'SOFTWARE'), (52, 72, 'TYPE'), (72, 84, 'TYPE')]}),
    ("openjdk 22", {'entities': [(0, 7, 'SOFTWARE'), (8, 10, 'VERSIONS')]}),
    ("eclipse 2024-06", {'entities': [(0, 7, 'SOFTWARE'), (8, 12, 'VERSIONS'), (13, 15, 'VERSIONS')]}),
    ("Microstation.", {'entities': [(0, 12, 'SOFTWARE')]}),
    ("Microstation.", {'entities': [(0, 12, 'SOFTWARE')]}),
    ("Microstation.", {'entities': [(0, 12, 'SOFTWARE')]}),
    ("Microstation.", {'entities': [(0, 12, 'SOFTWARE')]}),
    ("Microstation latest", {'entities': [(0, 12, 'SOFTWARE'), (13, 19, 'VERSIONS')]}),
    ("sts 4", {'entities': [(0, 3, 'SOFTWARE'), (4, 5, 'VERSIONS')]}),
    ("powerbi 2.12", {'entities': []}),
    ("Please help to complete installation process for postgresql software_x000D_ | TYPE: Act", {'entities': [(24, 36, 'TASK'), (49, 59, 'SOFTWARE'), (75, 87, 'TYPE'), (12, 23, 'JUSTIFICATIONS')]}),
    ("installation of node js | TYPE: Act", {'entities': [(0, 12, 'TASK'), (16, 23, 'SOFTWARE'), (23, 35, 'TYPE')]}),
    ("manual installation of  Eclispe   against WASP-Operations Team approval .", {'entities': []}),
    ("manual installation of  Open JDK  against WASP-Operations Team approval . | TYPE: Act", {'entities': [(7, 19, 'TASK'), (24, 32, 'SOFTWARE'), (73, 85, 'TYPE'), (82, 85, 'TYPE')]}),
    ("manual installation of  Python  against WASP-Operations Team approval . | TYPE: Act", {'entities': [(7, 19, 'TASK'), (24, 30, 'SOFTWARE'), (71, 83, 'TYPE'), (80, 83, 'TYPE')]}),
    ("need to install notepad++ | TYPE: Act", {'entities': [(8, 15, 'TASK'), (16, 25, 'SOFTWARE'), (25, 37, 'TYPE')]}),
    ("manual installation of  Notepad++  against WASP-Operations Team approval . | TYPE: Act", {'entities': [(7, 19, 'TASK'), (24, 33, 'SOFTWARE'), (74, 86, 'TYPE'), (83, 86, 'TYPE')]}),
    ("manual installation of  Grammarly  against WASP-Operations Team approval. | TYPE: Act", {'entities': [(7, 19, 'TASK'), (24, 33, 'SOFTWARE'), (73, 85, 'TYPE'), (82, 85, 'TYPE')]}),
    ("manual installation of  Microsoft Visio Professional  against WASP-Operations Team approval . | TYPE: Act", {'entities': [(7, 19, 'TASK'), (24, 39, 'SOFTWARE'), (93, 105, 'TYPE'), (102, 105, 'TYPE'), (40, 52, 'LICENSES')]}),
    ("Request to install Notepad++, Microsoft azure storage explorer, SAP Logon | TYPE: Act", {'entities': [(0, 7, 'TASK'), (19, 28, 'SOFTWARE'), (73, 85, 'TYPE'), (40, 62, 'SOFTWARE'), (82, 85, 'TYPE'), (64, 73, 'SOFTWARE')]}),
    ("Hi Team,_x000D_ | TASK: install | SOFTWARE: Android Studio | TYPE: Act | TARGETS: System", {'entities': [(15, 31, 'TASK'), (31, 58, 'SOFTWARE'), (58, 70, 'TYPE'), (70, 88, 'TARGETS')]}),
    ("please install power bi app | TYPE: Act", {'entities': [(7, 14, 'TASK'), (15, 23, 'SOFTWARE'), (27, 39, 'TYPE')]}),
    ("Requesting software team assistance for setting up git. facing error and not recognising on command prompt.", {'entities': [(51, 54, 'SOFTWARE')]}),
    ("Unable to install SAP GUI & HANA Studio to access BW on HANA, BW/4 HANA applications. So Please install the same in my machine. | TYPE: Not able to | TYPE: Act", {'entities': [(43, 49, 'TASK'), (18, 25, 'SOFTWARE'), (127, 147, 'TYPE'), (147, 159, 'TYPE'), (156, 159, 'TYPE'), (119, 126, 'TARGETS')]}),
    ("manual installation of  Oracle Database 21c express editon  against WASP-Operations Team approval . | TYPE: Act", {'entities': [(7, 19, 'TASK'), (24, 39, 'SOFTWARE'), (99, 111, 'TYPE'), (108, 111, 'TYPE'), (40, 43, 'VERSIONS')]}),
    ("manual installation of  Microsoft Visio Professional  against WASP-Operations Team approval . | TYPE: Act", {'entities': [(7, 19, 'TASK'), (24, 39, 'SOFTWARE'), (93, 105, 'TYPE'), (102, 105, 'TYPE'), (40, 52, 'LICENSES')]}),
    ("I am on free pool now. and have a Visual Studio Professional License valid till March 2025. I need Visual Studio Professional software for learning and assessment purpose.", {'entities': [(34, 47, 'SOFTWARE'), (86, 90, 'VERSIONS'), (135, 147, 'JUSTIFICATIONS'), (8, 12, 'LICENSES'), (48, 60, 'LICENSES')]}),
    ("Need to install Avaya. | TYPE: Act", {'entities': [(8, 15, 'TASK'), (22, 34, 'TYPE')]}),
]